# -*- coding: utf-8 -*-
"""14052026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11N5kWq1Heb_kyri20jUbdMZUx0Khso6N
"""

from abc import ABC, abstractmethod

# --- SOYUT SINIFLAR ---

class Kaynak(ABC):
    def __init__(self, baslik, kayit_no):
        self._baslik = baslik
        self._kayit_no = kayit_no

    @property
    def baslik(self):
        return self._baslik

    @baslik.setter
    def baslik(self, value):
        self._baslik = value

    @property
    def kayit_no(self):
        return self._kayit_no

    @kayit_no.setter
    def kayit_no(self, value):
        self._kayit_no = value

    @abstractmethod
    def __str__(self):
        pass


class Islem(ABC):
    @abstractmethod
    def ekle(self, item):
        pass

    @abstractmethod
    def sil(self, kayit_no):
        pass

    @abstractmethod
    def guncelle(self):
        pass

    @abstractmethod
    def listele(self):
        pass


# --- SOMUT SINIFLAR (KAYNAKLAR) ---

class Kitap(Kaynak):
    def __init__(self, baslik, kayit_no, yazar, sayfa_sayisi):
        super().__init__(baslik, kayit_no)
        self._yazar = yazar
        self._sayfa_sayisi = sayfa_sayisi

    @property
    def yazar(self):
        return self._yazar

    @yazar.setter
    def yazar(self, value):
        self._yazar = value

    @property
    def sayfa_sayisi(self):
        return self._sayfa_sayisi

    @sayfa_sayisi.setter
    def sayfa_sayisi(self, value):
        self._sayfa_sayisi = value

    def __str__(self):
        return f"Kitap: {self.baslik} | Kayıt No: {self.kayit_no} | Yazar: {self.yazar} | Sayfa: {self.sayfa_sayisi}"


class Dergi(Kaynak):
    def __init__(self, baslik, kayit_no, yayin_donemi, sayi_no):
        super().__init__(baslik, kayit_no)
        self._yayin_donemi = yayin_donemi
        self._sayi_no = sayi_no

    @property
    def yayin_donemi(self):
        return self._yayin_donemi

    @yayin_donemi.setter
    def yayin_donemi(self, value):
        self._yayin_donemi = value

    @property
    def sayi_no(self):
        return self._sayi_no

    @sayi_no.setter
    def sayi_no(self, value):
        self._sayi_no = value

    def __str__(self):
        return f"Dergi: {self.baslik} | Kayıt No: {self.kayit_no} | Dönem: {self.yayin_donemi} | Sayı: {self.sayi_no}"


# --- SOMUT SINIFLAR (İŞLEMLER) ---

class KitapIslem(Islem):
    kitap_sayisi = 0 

    def __init__(self):
        self._kitaplar = []

    def ekle(self, kitap):

        for k in self._kitaplar:
            if k.kayit_no == kitap.kayit_no:
                print("Hata: Bu kayıt numarası ile zaten bir kitap mevcut!")
                return

        self._kitaplar.append(kitap)
        KitapIslem.kitap_sayisi += 1
        print("\nKitap başarıyla eklendi.")
        print(f"Toplam Kitap Sayısı: {KitapIslem.kitap_sayisi}")

    def sil(self, kayit_no):
        for kitap in self._kitaplar:
            if kitap.kayit_no == kayit_no:
                self._kitaplar.remove(kitap)
                KitapIslem.kitap_sayisi -= 1
                print("Kitap başarıyla silindi.")
                return
        print("Hata: Belirtilen kayıt numarasına sahip kitap bulunamadı.")

    def guncelle(self):
        while True:
            kayit_no = input("Güncellemek istediğiniz kitabın kayıt numarasını girin (iptal için 'iptal' yazın): ")
            if kayit_no.lower() == 'iptal':
                print("Kitap güncelleme işlemi iptal edildi.")
                return

            found_kitap = None
            for kitap in self._kitaplar:
                if kitap.kayit_no == kayit_no:
                    found_kitap = kitap
                    break

            if found_kitap:
                print("Yeni bilgileri giriniz (Boş bırakılan alanlar değiştirilmez):")
                yeni_baslik = input(f"Yeni Başlık (Mevcut: {found_kitap.baslik}): ")
                yeni_yazar = input(f"Yeni Yazar (Mevcut: {found_kitap.yazar}): ")
                yeni_sayfa = input(f"Yeni Sayfa Sayısı (Mevcut: {found_kitap.sayfa_sayisi}): ")

                if yeni_baslik: found_kitap.baslik = yeni_baslik
                if yeni_yazar: found_kitap.yazar = yeni_yazar
                if yeni_sayfa: found_kitap.sayfa_sayisi = yeni_sayfa

                print("Kitap başarıyla güncellendi.")
                return
            else:
                print("Hata: Belirtilen kayıt numarasına sahip kitap bulunamadı. Lütfen tekrar deneyin veya 'iptal' yazın.")

    def listele(self):
        
        if not self._kitaplar:
            print("Kayıt bulunamadı.")
            return
        print("\n--- Kitap Listesi ---")
        for kitap in self._kitaplar:
            print(kitap)


class DergiIslem(Islem):
    dergi_sayisi = 0

    def __init__(self):
        self._dergiler = []

    def ekle(self, dergi):
        for d in self._dergiler:
            if d.kayit_no == dergi.kayit_no:
                print("Hata: Bu kayıt numarası ile zaten bir dergi mevcut!")
                return

        self._dergiler.append(dergi)
        DergiIslem.dergi_sayisi += 1
        print("\nDergi başarıyla eklendi.")
        print(f"Toplam Dergi Sayısı: {DergiIslem.dergi_sayisi}")

    def sil(self, kayit_no):
        for dergi in self._dergiler:
            if dergi.kayit_no == kayit_no:
                self._dergiler.remove(dergi)
                DergiIslem.dergi_sayisi -= 1
                print("Dergi başarıyla silindi.")
                return
        print("Hata: Belirtilen kayıt numarasına sahip dergi bulunamadı.")

    def guncelle(self):
        while True:
            kayit_no = input("Güncellemek istediğiniz derginin kayıt numarasını girin (iptal için 'iptal' yazın): ")
            if kayit_no.lower() == 'iptal':
                print("Dergi güncelleme işlemi iptal edildi.")
                return

            found_dergi = None
            for dergi in self._dergiler:
                if dergi.kayit_no == kayit_no:
                    found_dergi = dergi
                    break

            if found_dergi:
                print("Yeni bilgileri giriniz (Boş bırakılan alanlar değiştirilmez):")
                yeni_baslik = input(f"Yeni Başlık (Mevcut: {found_dergi.baslik}): ")
                yeni_donem = input(f"Yeni Yayın Dönemi (Mevcut: {found_dergi.yayin_donemi}): ")
                yeni_sayi = input(f"Yeni Sayı No (Mevcut: {found_dergi.sayi_no}): ")

                if yeni_baslik: found_dergi.baslik = yeni_baslik
                if yeni_donem: found_dergi.yayin_donemi = yeni_donem
                if yeni_sayi: found_dergi.sayi_no = yeni_sayi

                print("Dergi başarıyla güncellendi.")
                return
            else:
                print("Hata: Belirtilen kayıt numarasına sahip dergi bulunamadı. Lütfen tekrar deneyin veya 'iptal' yazın.")

    def listele(self):
        if not self._dergiler:
            print("Kayıt bulunamadı.")
            return
        print("\n--- Dergi Listesi ---")
        for dergi in self._dergiler:
            print(dergi)


# --- MENÜ SINIFI VE ANA DÖNGÜ ---

class Menu:
    @staticmethod
    def goster():
        print("\n" + "="*30)
        print("1. Kitap Ekle")
        print("2. Kitap Sil")
        print("3. Kitap Güncelle")
        print("4. Kitapları Listele")
        print("5. Dergi Ekle")
        print("6. Dergi Sil")
        print("7. Dergi Güncelle")
        print("8. Dergileri Listele")
        print("9. Çıkış")
        print("="*30)



if __name__ == "__main__":
    kitap_islemleri = KitapIslem()
    dergi_islemleri = DergiIslem()

    while True:
        Menu.goster()
        secim = input("Yapmak istediğiniz işlemi seçin (1-9): ")

        if secim == '1':
            baslik = input("Kitabın başlığını girin: ")
            kayit_no = input("Kitabın kayıt numarasını girin: ")
            yazar = input("Kitabın yazarını girin: ")
            sayfa = input("Kitabın sayfa sayısını girin: ")
            yeni_kitap = Kitap(baslik, kayit_no, yazar, sayfa)
            kitap_islemleri.ekle(yeni_kitap)

        elif secim == '2':
            kayit_no = input("Silmek istediğiniz kitabın kayıt numarasını girin: ")
            kitap_islemleri.sil(kayit_no)

        elif secim == '3':
            kitap_islemleri.guncelle()

        elif secim == '4':
            kitap_islemleri.listele()

        elif secim == '5':
            baslik = input("Derginin başlığını girin: ")
            kayit_no = input("Derginin kayıt numarasını girin: ")
            donem = input("Derginin yayın dönemini girin: ")
            sayi = input("Derginin sayı numarasını girin: ")
            yeni_dergi = Dergi(baslik, kayit_no, donem, sayi)
            dergi_islemleri.ekle(yeni_dergi)

        elif secim == '6':
            kayit_no = input("Silmek istediğiniz derginin kayıt numarasını girin: ")
            dergi_islemleri.sil(kayit_no)

        elif secim == '7':
            dergi_islemleri.guncelle()

        elif secim == '8':
            dergi_islemleri.listele()

        elif secim == '9':
            print("Sistemden çıkılıyor. İyi günler!")
            break

        else:
            print("Hatalı giriş! Lütfen 1 ile 9 arasında bir seçim yapın.")